---
title: "Homework 5 - Iteration"
author: "Sydney Ng (uni: sn2863)"
date: "Due 11/18/2020 by 10:00 pm ET"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(purrr)
```

### Problem 1

```{r}
homicide_df <-
  read_csv("./homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "Unsolved",
      disposition == "Open/No arrest" ~ "Unsolved",
      disposition == "Closed by arrest" ~ "Resolved"
    )
  ) %>%
  select(city_state, resolved) %>%
  filter(city_state != "Tulsa_AL")

aggregate_df <-
  homicide_df %>%
  group_by(city_state) %>%
  summarize(
    homicide_total = n(),
    homicide_unsolved = sum(resolved == "Unsolved")
  )
```

Can we do a test for proportions for a specific city?
```{r}
prop.test(
  aggregate_df %>% filter(city_state=="Baltimore_MD") %>% pull(homicide_unsolved),
  aggregate_df %>% filter(city_state=="Baltimore_MD") %>% pull(homicide_total)) %>%
  broom::tidy()
```

Iterate:
```{r}
prop_results <-
  aggregate_df %>%
  mutate(
    prop_tests = map2(.x = homicide_unsolved, .y = homicide_total,
                      ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>% # unpacks the prop.test results as their own columns
  select(city_state, estimate, conf.low, conf.high)

prop_results %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1)) +
  geom_errorbar(aes(ymin=conf.low, ymax=conf.high)) +
  labs(
    title = "Distribution of Homicide Rates",
    x = "Location (City_State)",
    y = "Estimate of Proportion",
    caption = "caption here."
  )
```

### Problem 2 and 3 notes from class
```{r, eval=FALSE}
# importing one dataset at a time...
data_1 <- read_csv("./longitudinal_data/con_01.csv")

#but, we want to start with a list of our file names!
path_df <- tibble(path = list.files("longitudinal_data")) %>%
  mutate(
    path = str_c("longitudinal_data/", path),
    data = map(.x = path, ~read_csv(.x)) # this is the hard part of the hw
    ) %>%
  select(-path) %>%
  unnest(data)

read.csv(path_df$path[[1]])

# gotta tidy the rest of this dataset! there is a data organization problem, 
# that comes up from time to time, that we also have to deal with for the homework!
# we want one dataset that is tidy with all of the observations from all csv's
```



### Problem 3 Simulation

```{r eval=FALSE}
sim_t <- function(mu){
  sim_data <- tibble(
    tibble(
      true_mu = mu, # decided to have the true mean in the tibble
      x = rerun(5000, rnorm(n=30, mean=mu, sd=5))
    )) %>%
  mutate(
    t_tests = map(.x = x, ~t.test(x=.x, mu=0)),
    tidy_t = map(.x = t_tests, ~broom::tidy(.x))
    ) %>%
    select(-t_tests) %>%
    unnest(tidy_t) %>%
    select(true_mu, estimate, p.value)
}

output <- vector("list", 7)
for (i in 1:7){
  output[[i]] = sim_t(i-1) %>% # for values of mu = 0 to 6
    bind_rows
}

```



